### ISSUE TITLE
OSCLOUD binary version is built against pcl-1.10

### ISSUE THREAD

**Issue by okasha55** [ros-melodic-arch/ros-melodic-pcl-ros#2]
as the title said the oscloud binary version of this package is built against pcl-1.10 while the provided pcl binary is 1.9 which causes this error.
`Project 'pcl_ros' specifies '/usr/include/pcl-1.10' as an include dir, which is not found.`
building pcl-1.10 from source causes some problems for me.
so I built this package against the binary pcl-1.9 available on oscloud, and it worked fine.
I suggest either building this package's binary against pcl-1.9 or update the binary pcl to 1.10.

**Comment by bionade24** [comment]
Sorry, but docker changed something and my building doesn't work at the moment. I didn't have time to investigate the issue yet. I'm aware of all other issues, too. But at the moment you have to build yourself or not upgrade.

**Comment by bionade24** [comment]
PCL-1.10 is now available.
